name: scp browser
on: 
  push:
    branches:
      - main
jobs:
  DeployBrowser:
    name: scp browser
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LOWORBITHOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        source: "public"
        target: "/home/${{ secrets.USERNAME }}/containers/server_browser/public/"
        overwrite: 1
