name: scp browser
on: 
  push:
    branches:
      - main
jobs:
  DeployMaps:
    name: scp browser
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LOWORBITHOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        source: "."
        target: "/home/${{ secrets.USERNAME }}/containers/server_browser/temp"
        overwrite: 1

  CopyLocal:
    name: Copy Local Files
    needs: [DeployMaps, DeployVoteConfig]
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LOWORBITHOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: echo ${{ secrets.PASSWORD }} | sudo -S cp /home/${{ secrets.USERNAME }}/containers/server_browser/temp/* /home/${{ secrets.USERNAME }}/containers/server_browser/public/*
